export { default as AnimatedH2 } from './AnimatedH2';
export { default as Box } from './Box';
export { default as Caption } from './Caption';
export { default as DashedP } from './DashedP';
export { default as H1 } from './H1';
export { default as H2 } from './H2';
export { default as H3 } from './H3';
export { default as P } from './P';
export { default as Span } from './Span';
